# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0 # Updated version
      hooks:
          - id: trailing-whitespace
            exclude: "tests/testdata/"
          - id: end-of-file-fixer
            exclude: "tests/testdata/"
          - id: check-yaml
          - id: check-added-large-files
            args: ["--maxkb=5000"]
    - repo: https://github.com/kynan/nbstripout
      rev: 0.6.1 # Updated version
      hooks:
          - id: nbstripout
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.3.6
      hooks:
          - id: ruff
            args: [--fix, --exit-non-zero-on-fix]
          - id: ruff-format
