# Common inference parameters
batch_size: 8
val_batch_size: 8
n_samples_wta: 5 # number of samples for evaluating coverage
save_wta_to_disk: False # save to disk for further examination

# Augmentation settings
augment_train: null # Options: "pcd", "image", or null
augment_cfg:
