name: dino_3dgp

# Model settings
type: cross_displacement # Type of model
use_text_embedding: True # If true, expects (siglip) text embedding to be provided as input and uses as another token
use_gripper_token: True # Adds an additional gripper token
num_transformer_layers: 4 # num blocks for self atttention
dino_model: 'facebook/dinov2-base'

is_gmm: True # Train a GMM and minimize negative log likelihood instead
fixed_variance: [0.01, 0.05, 0.1, 0.25, 0.5] # for gmm
uniform_weights_coeff: 0.1 # coefficient for nll loss term when we use uniform mixing weights instead of pred
