defaults:
  - base_dataset # Inherit from base
name: rpadLerobot

# The LeRobot dataset repo containing post-processed goals.
# # Overriding this means you have to do LEROBOT_HOME / repo_id directly in data_dir.
data_dir: null # don't want to override automatic computation, unless you do...
repo_id: sriramsk/droid_lerobot
use_subgoals: False

val_episode_ratio: 0.05 # percent of episodes in val set

# Multi-camera configuration (first camera is primary)
cameras:
  - name: cam_1
    color_key: "observation.images.cam_1.color"
    depth_key: "observation.images.cam_1.depth"
  - name: cam_2
    color_key: "observation.images.cam_2.color"
    depth_key: "observation.images.cam_2.depth"

gripper_pcd_key: "observation.points.gripper_pcds"

rgb_feat: False # If true, compute DINOv2 features, else just return RGB
