defaults:
  - base_dataset # Inherit from base
name: rpadFoxglove

additional_img_dir: null
data_sources: # List of data sources
  - human
  - aloha
rgb_feat: False # If true, compute DINOv2 features, else just return RGB
use_intermediate_frames: True # Use all intermediate frames in [start, end] as input to the model instead of only the start frame.
