defaults:
  - base_dataset # Inherit from base
name: rpadFoxglove

additional_img_dir: null
data_sources: # List of data sources
  - human
  - aloha
rgb_text_feat: False # Enable/disable computation of rgb/text features
use_intermediate_frames: True # Use all intermediate frames in [start, end] as input to the model instead of only the start frame.
