defaults:
  - base_dataset # Inherit from base
name: rpadFoxglove
data_name: "0627" # Name of dataset to select splits for

additional_img_dir: null
data_sources: # List of data sources
  - human
  - aloha
oversample_robot: True # If true, oversample the robot data to equalize the amounts of the two data sources in an epoch

rgb_feat: False # If true, compute DINOv2 features, else just return RGB
use_full_text: True # Combine all subgoal captions into one and use the same caption for the whole demo
use_intermediate_frames: True # Use all intermediate frames in [start, end] as input to the model instead of only the start frame.

# Only meaningful to set to True if use_full_text=False
use_gemini_subgoals: False
