name: rpadFoxglove
data_dir: ""
cache_dir: null
type: cross_displacement # (flow, point) Type of dataset
data_sources: # List of data sources
  - human
  - aloha

train_size: null # (int, null) Length of the train dataset
val_size: null # (int, null) Length of the validation dataset
