name: rt1
data_dir: ""
cache_dir: null

train_size: null # (int, null) Length of the train dataset
val_size: null # (int, null) Length of the validation dataset
num_points: 8192 # points in pcd
max_depth: 1 # filter out pcd beyond this depth
