augment_train: "pcd" # Options: "pcd", "image", or null
augment_cfg:
  augment_prob: 0.75 # Probability of augmentation (the actual augmentation prob also depends on cache_invalidation_rate)
  pcd:
    augment_transform: True
    pcd_sample: ["voxel", "fps"]
    fps_num_points: [4096, 8192]
    voxel_size: [0.01, 0.02]
  image:
    color_jitter_prob: 0.8
    brightness: 0.2
    contrast: 0.2
    saturation: 0.2
    hue: 0.1
    grayscale_prob: 0.1
    blur_prob: 0.1
    blur_kernel_size: 1
