# Common training parameters
lr: 1e-4
lr_warmup_steps: 100
weight_decay: 1e-5
epochs: 250
precision: 32
batch_size: 8
val_batch_size: 8
grad_clip_norm: 0.3
num_training_steps: None # Set by the training loop.

check_val_every_n_epochs: 10
additional_train_logging_period: 100 # Global step period to log additional training metrics

n_samples_wta: 5 # number of samples for evaluating coverage
save_wta_to_disk: False # save to disk for further examination

# Augmentation settings
augment_train: "pcd" # Options: "pcd", "image", or null
augment_cfg:
  augment_prob: 0.75 # Probability of augmentation (the actual augmentation prob also depends on cache_invalidation_rate)
  pcd:
    augment_transform: True
    pcd_sample: ["voxel", "fps"]
    fps_num_points: [4096, 8192]
    voxel_size: [0.01, 0.02]
  image:
    hflip_prob: 0.5
    rotate_prob: 0.3
    crop_resize_prob: 0.3
    crop_size_range: [192, 224]

    color_jitter_prob: 0.3
    brightness: 0.2
    contrast: 0.2
    saturation: 0.2
    hue: 0.1

    grayscale_prob: 0.1

    blur_prob: 0.1
    blur_kernel_size: 1
