defaults:
  - base_train

epochs: 1000
precision: 16-mixed
check_val_every_n_epochs: 25
additional_train_logging_period: 1000

# ModelCheckpoint configurations
checkpoints:
  rmse:
    monitor: val/rmse
    mode: min
  rmse_and_std_combi:
    monitor: val/rmse_and_std_combi
    mode: min
