defaults:
  - base_train

epochs: 500
precision: 16-mixed
batch_size: 16
val_batch_size: 16
check_val_every_n_epochs: 25

# ModelCheckpoint configurations
checkpoints:
  rmse:
    monitor: val/rmse
    mode: min
  rmse_and_std_combi:
    monitor: val/rmse_and_std_combi
    mode: min
