mode: train

# This is somewhat arbitrary.
job_type: ${mode}_${dataset.name}

defaults:
  # Each of these have their own configuration parameters.
  - dataset: cifar10
  - model: vit

  # We assume a different training config for each dataset/model pair.
  - training: ${dataset}_${model}

  # Simple shared imports.
  - _logging

  # Override.
  - _self_

seed: 42

resources:
  num_workers: 16
  gpus:
    - 0

load_checkpoint: False
checkpoint:
  # If we want to load a model for a specific run, we can change that here.
  run_id: False
  type: rmse
  reference: ${wandb.entity}/${wandb.project}/best_${checkpoint.type}_model-${checkpoint.run_id}:best

wandb:
  # Assume no group provided, we will create a default one.
  group: Null
